//
//  CTSConstants.h
//  RSS Reader
//
//  Created by Srikanth on 7/12/14.
//
//

#define FEED_CELL_TITLE_LABEL_MAX_WIDTH 260
#define FEED_CELL_DESCRIPTION_LABEL_MAX_WIDTH 160

#define FEED_CELL_TITLE_LABEL_FONT_SIZE 14
#define FEED_CELL_DESCRIPTION_LABEL_FONT_SIZE 14

#define FEED_CELL_ELEMENTS_TOP_PADDING 9
#define FEED_CELL_ELEMENTS_MIDDLE_PADDING 0
#define FEED_CELL_ELEMENTS_BOTTOM_PADDING 20